### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by ericmjonas** [ericmjonas/pywren#22]
Both the client-side and the server-side runtime would need a little bit of work for python3 support. 
### Server-side
- [ ] the fabfile `fabfile_builder.py` handles spinning up an EC2 instance, downloading anaconda, configuring it, tarballing the result, and cramming it back into S3 as the run environment. You'd just need to download the python3 miniconda -- everything there should basically work ok. 
- [ ] `jobrunner.py` would need to be python3 friendly
### Client-side
- [ ] as @tdhopper has pointed out with some issues, there's just a host of non-python-3 friendly code and idioms in there. all of them could be fixed and I think some of the more complex parts (cloudpickle?) already have python 3 support

Additionally we'd want to properly set up a build matrix on travis for testing

See also issues #21  #19  #20

**Comment by washcycle** [comment]
I'm working on a fork that will run on python 3. If I get it working i'll share it. I did find one snafu in my journeys.

The python 3 StringIO doesn't accept `bytes` arguments.

"If you need to write code that runs on 2.7 and 3.x, use the BytesIO class in the io module." source:
http://stackoverflow.com/questions/6479100/python-stringio-replacement-that-works-with-bytes-instead-of-strings

**Comment by ericmjonas** [comment]
Ok this is incredibly awesome! I've been hacking a lot on this lately -- I think there's also the issue of the anaconda runtime. Want to coordinate together? This is so great!

**Comment by washcycle** [comment]
Sure thing. I'm hacking it together too, then I was going to go back and make sure 2.7 still worked. Is 2.7 the cutoff for backwards compatibility? I'm CST, so  i'm going to call it a night, but I think I made a decent dent. I'm trying to get the simpletest.py to run. I got as far as uploading the pickles to s3, but then it hangs with no status or error messages.

```
(data-sci) hiro@deathscythe /data/Development/python/pywren $ python examples/simpletest.py
a60b6278-4398-4037-83fe-286109ab77c3
```

```
hiro@deathscythe /data/Development/python/pywren $ aws s3 ls s3://pywern/pywren.jobs/a60b6278-4398-4037-83fe-286109ab77c3/
2017-02-10 23:21:14          5 aggdata.pickle
2017-02-10 23:21:15     204286 lambda.pickle
```

Yeah yeah, I spelt the bucket name wrong.

**Comment by ericmjonas** [comment]
Awesome, any chance you have a public fork I can take a look at?

**Comment by washcycle** [comment]
I committed my work and pushed it here: https://github.com/washcycle/pywren

**Comment by ericmjonas** [comment]
Ok I just pushed a bunch of the stand-alone reducer functionality to master, and then created a python3 branch with an updated travis config to test python 3. It will fail for a while :)

**Comment by ericmjonas** [comment]
I created a python3 runtime at s3://ericmjonas-public/condaruntime.python3.stripped.scipy-cvxpy-sklearn.mkl_avx2.tar.gz  -- you should be able to set your yaml to point to it and have a python runtime on the remote side.

**Comment by ericmjonas** [comment]
I cherrypicked your commit and you did an awesomely-clean job, @washcycle ! I found a few things: 

1. cloudpickle has some bugs with python3.6, but not python3.5. 

2. In the lambda wrenhandler, I unpickle the function object to get the python module source code that we've sent along. This is actually pretty bad because wrenhandler runs inside the old-and-busted lambda python runtime. I think I'm going to have to change the format of the pickled function to make this work, which is a bigger change than I was planning. 

I'm going to try and address item right now, we'll see how much work it is.

**Comment by washcycle** [comment]
Excellent, haven't had a chance to work on it again this weekend. Did you
commit the changes to your branch? Should I keep moving with what I have in
the meantime?

**Comment by ericmjonas** [comment]
Ok, check out the python3 branch -- I think we're incredibly close. There are some import complications that I had to hack around because of the way that lambda's python 2.7 invokes things (hence some gross hacks around imports). 

I fixed issue (2) above by passing the function as a json-serialized string instead of an actual pickle object so that it can be unpickled by both python2 and python3. Along the way I got to learn all about the differences between bytes and strings and encodings and pickling. 

My plan right now is to try and get travis working for both python2 and python3.5 with the latest code change, and then try and clean it up. I'll post on this issue in an hour or so when I have it working and would love to get your feedback before merging into mainline. 

Also now that we're getting interest, can I list you in the soon-to-be-created `CONTRIBUTORS.md`?

**Comment by washcycle** [comment]
Will be happy to look it over. Feel free to add me to the list. I'm pretty excited about this!

**Comment by ericmjonas** [comment]
Ok I have a pull request up on the master branch that I'd love your
feedback on!

**Comment by washcycle** [comment]
Great! Will do when I get home ;) I did notice in the python3 branch last night that when I ran `create_config` it wasn't pointing to the python 3 run-time on your public s3 in the `.pyrewn_config`. Maybe you addressed that already.

**Comment by ericmjonas** [comment]
So now `create_config` has a --pythonver version that should be set to
"3.5" when you create the config. I really need to think of a more
consistent way of versioning these runtimes.

**Comment by washcycle** [comment]
I had a thought on this. We could check the version in the function that creates the config and use that to select the runtime. Similar to what was done with the python imports I don't see why that wouldn't work in this case. I am thinking we might want to also consider two config files for people who utilize both environments `.pywren_config3` and `.pywren_config2`. If you this this is a good idea I think it is something I am willing to tackle.

**Comment by ericmjonas** [comment]
With @ooq's recent commits `create-config` now automatically picks the right python runtime, I'm going to say that we have working python3 support and close the issue!
