### ISSUE TITLE
Reduce setup time

### ISSUE THREAD

**Issue by ericmjonas** [ericmjonas/pywren#25]
Sometimes we find old runtimes in /tmp, I think this is because AWS recycles my lambda runner. This could potentially be used to cache the runtime and dramatically reduce setup time.

**Comment by shivaram** [comment]
Not sure if the cache has tar.gz files or an entire tree -- but one easy thing to do might be to check the md5sum of the pydata tar.gz if it exists

**Comment by JMBattista** [comment]
Lambda will, sometimes, recycle the container your function runs in. This blog post mentions node but it applies to all the language options: https://aws.amazon.com/blogs/compute/container-reuse-in-lambda/

Its important to note that they guarantee you get a fresh container if you've updated your Lambda code.

**Comment by ericmjonas** [comment]
Closed with latest push to master by caching runtime based on s3 ETag. Test now exists to check this behavior. 

```
$ python latency_measure.py
invoke 1: 
runtime was cached:  False
no cache, invoke latency= 18.93s
invoke 2: 
runtime was cached:  True
with cache, invoke latency= 5.35s
```
