### ISSUE TITLE
PyWren IAM role should use correct AWS id

### ISSUE THREAD

**Issue by shivaram** [ericmjonas/pywren#28]
The IAM role installed by `pywren_exec_role` doesn't have the right permissions for the cloud watch logging actions. We need to get the user's aws id from boto to get this right.

**Comment by ericmjonas** [comment]
For posterity, this arose when @shivaram was looking for logs in cloudwatch. We should make the command-line print-out cloudwatch logs and then add unit testing to make sure logs are showing up.

**Comment by shivaram** [comment]
The unit test is a good idea. Also we could print out the URL to cloud watch from the CLI. For me it looks something like https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logStream:group=/aws/lambda/pywren1

**Comment by shivaram** [comment]
@ericmjonas You'll also need to update the IAM role at https://github.com/ericmjonas/pywren/blob/83b7b92c93a6890284573731de2b29e222facdd1/pywren/wrenconfig.py#L89 ?
